name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"  # runs at 00:00 and 12:00 UTC every day
  workflow_dispatch: # manual trigger
  push:
    branches:
      - main # run on pushes to the main branch

jobs:
  generate:
    permissions:
      contents: write # needed to push to the output branch
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: flying-bison01
          outputs: dist/snake.svg?palette=github-dark

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
